// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: pb/biscuit.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicKey_Algorithm int32

const (
	PublicKey_Ed25519 PublicKey_Algorithm = 0
)

// Enum value maps for PublicKey_Algorithm.
var (
	PublicKey_Algorithm_name = map[int32]string{
		0: "Ed25519",
	}
	PublicKey_Algorithm_value = map[string]int32{
		"Ed25519": 0,
	}
)

func (x PublicKey_Algorithm) Enum() *PublicKey_Algorithm {
	p := new(PublicKey_Algorithm)
	*p = x
	return p
}

func (x PublicKey_Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublicKey_Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_biscuit_proto_enumTypes[0].Descriptor()
}

func (PublicKey_Algorithm) Type() protoreflect.EnumType {
	return &file_pb_biscuit_proto_enumTypes[0]
}

func (x PublicKey_Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PublicKey_Algorithm) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PublicKey_Algorithm(num)
	return nil
}

// Deprecated: Use PublicKey_Algorithm.Descriptor instead.
func (PublicKey_Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{2, 0}
}

type OpUnary_Kind int32

const (
	OpUnary_Negate OpUnary_Kind = 0
	OpUnary_Parens OpUnary_Kind = 1
	OpUnary_Length OpUnary_Kind = 2
)

// Enum value maps for OpUnary_Kind.
var (
	OpUnary_Kind_name = map[int32]string{
		0: "Negate",
		1: "Parens",
		2: "Length",
	}
	OpUnary_Kind_value = map[string]int32{
		"Negate": 0,
		"Parens": 1,
		"Length": 2,
	}
)

func (x OpUnary_Kind) Enum() *OpUnary_Kind {
	p := new(OpUnary_Kind)
	*p = x
	return p
}

func (x OpUnary_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpUnary_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_biscuit_proto_enumTypes[1].Descriptor()
}

func (OpUnary_Kind) Type() protoreflect.EnumType {
	return &file_pb_biscuit_proto_enumTypes[1]
}

func (x OpUnary_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *OpUnary_Kind) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = OpUnary_Kind(num)
	return nil
}

// Deprecated: Use OpUnary_Kind.Descriptor instead.
func (OpUnary_Kind) EnumDescriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{13, 0}
}

type OpBinary_Kind int32

const (
	OpBinary_LessThan       OpBinary_Kind = 0
	OpBinary_GreaterThan    OpBinary_Kind = 1
	OpBinary_LessOrEqual    OpBinary_Kind = 2
	OpBinary_GreaterOrEqual OpBinary_Kind = 3
	OpBinary_Equal          OpBinary_Kind = 4
	OpBinary_Contains       OpBinary_Kind = 5
	OpBinary_Prefix         OpBinary_Kind = 6
	OpBinary_Suffix         OpBinary_Kind = 7
	OpBinary_Regex          OpBinary_Kind = 8
	OpBinary_Add            OpBinary_Kind = 9
	OpBinary_Sub            OpBinary_Kind = 10
	OpBinary_Mul            OpBinary_Kind = 11
	OpBinary_Div            OpBinary_Kind = 12
	OpBinary_And            OpBinary_Kind = 13
	OpBinary_Or             OpBinary_Kind = 14
	OpBinary_Intersection   OpBinary_Kind = 15
	OpBinary_Union          OpBinary_Kind = 16
	OpBinary_NotEqual       OpBinary_Kind = 17
)

// Enum value maps for OpBinary_Kind.
var (
	OpBinary_Kind_name = map[int32]string{
		0:  "LessThan",
		1:  "GreaterThan",
		2:  "LessOrEqual",
		3:  "GreaterOrEqual",
		4:  "Equal",
		5:  "Contains",
		6:  "Prefix",
		7:  "Suffix",
		8:  "Regex",
		9:  "Add",
		10: "Sub",
		11: "Mul",
		12: "Div",
		13: "And",
		14: "Or",
		15: "Intersection",
		16: "Union",
		17: "NotEqual",
	}
	OpBinary_Kind_value = map[string]int32{
		"LessThan":       0,
		"GreaterThan":    1,
		"LessOrEqual":    2,
		"GreaterOrEqual": 3,
		"Equal":          4,
		"Contains":       5,
		"Prefix":         6,
		"Suffix":         7,
		"Regex":          8,
		"Add":            9,
		"Sub":            10,
		"Mul":            11,
		"Div":            12,
		"And":            13,
		"Or":             14,
		"Intersection":   15,
		"Union":          16,
		"NotEqual":       17,
	}
)

func (x OpBinary_Kind) Enum() *OpBinary_Kind {
	p := new(OpBinary_Kind)
	*p = x
	return p
}

func (x OpBinary_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpBinary_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_biscuit_proto_enumTypes[2].Descriptor()
}

func (OpBinary_Kind) Type() protoreflect.EnumType {
	return &file_pb_biscuit_proto_enumTypes[2]
}

func (x OpBinary_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *OpBinary_Kind) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = OpBinary_Kind(num)
	return nil
}

// Deprecated: Use OpBinary_Kind.Descriptor instead.
func (OpBinary_Kind) EnumDescriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{14, 0}
}

type Policy_Kind int32

const (
	Policy_Allow Policy_Kind = 0
	Policy_Deny  Policy_Kind = 1
)

// Enum value maps for Policy_Kind.
var (
	Policy_Kind_name = map[int32]string{
		0: "Allow",
		1: "Deny",
	}
	Policy_Kind_value = map[string]int32{
		"Allow": 0,
		"Deny":  1,
	}
)

func (x Policy_Kind) Enum() *Policy_Kind {
	p := new(Policy_Kind)
	*p = x
	return p
}

func (x Policy_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Policy_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_biscuit_proto_enumTypes[3].Descriptor()
}

func (Policy_Kind) Type() protoreflect.EnumType {
	return &file_pb_biscuit_proto_enumTypes[3]
}

func (x Policy_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Policy_Kind) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Policy_Kind(num)
	return nil
}

// Deprecated: Use Policy_Kind.Descriptor instead.
func (Policy_Kind) EnumDescriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{15, 0}
}

type Biscuit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootKeyId     *uint32                `protobuf:"varint,1,opt,name=rootKeyId" json:"rootKeyId,omitempty"`
	Authority     *SignedBlock           `protobuf:"bytes,2,req,name=authority" json:"authority,omitempty"`
	Blocks        []*SignedBlock         `protobuf:"bytes,3,rep,name=blocks" json:"blocks,omitempty"`
	Proof         *Proof                 `protobuf:"bytes,4,req,name=proof" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Biscuit) Reset() {
	*x = Biscuit{}
	mi := &file_pb_biscuit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Biscuit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Biscuit) ProtoMessage() {}

func (x *Biscuit) ProtoReflect() protoreflect.Message {
	mi := &file_pb_biscuit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Biscuit.ProtoReflect.Descriptor instead.
func (*Biscuit) Descriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{0}
}

func (x *Biscuit) GetRootKeyId() uint32 {
	if x != nil && x.RootKeyId != nil {
		return *x.RootKeyId
	}
	return 0
}

func (x *Biscuit) GetAuthority() *SignedBlock {
	if x != nil {
		return x.Authority
	}
	return nil
}

func (x *Biscuit) GetBlocks() []*SignedBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *Biscuit) GetProof() *Proof {
	if x != nil {
		return x.Proof
	}
	return nil
}

type SignedBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         []byte                 `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	NextKey       *PublicKey             `protobuf:"bytes,2,req,name=nextKey" json:"nextKey,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,req,name=signature" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedBlock) Reset() {
	*x = SignedBlock{}
	mi := &file_pb_biscuit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedBlock) ProtoMessage() {}

func (x *SignedBlock) ProtoReflect() protoreflect.Message {
	mi := &file_pb_biscuit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedBlock.ProtoReflect.Descriptor instead.
func (*SignedBlock) Descriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{1}
}

func (x *SignedBlock) GetBlock() []byte {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *SignedBlock) GetNextKey() *PublicKey {
	if x != nil {
		return x.NextKey
	}
	return nil
}

func (x *SignedBlock) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type PublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     *PublicKey_Algorithm   `protobuf:"varint,1,req,name=algorithm,enum=PublicKey_Algorithm" json:"algorithm,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_pb_biscuit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_pb_biscuit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{2}
}

func (x *PublicKey) GetAlgorithm() PublicKey_Algorithm {
	if x != nil && x.Algorithm != nil {
		return *x.Algorithm
	}
	return PublicKey_Ed25519
}

func (x *PublicKey) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type Proof struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*Proof_NextSecret
	//	*Proof_FinalSignature
	Content       isProof_Content `protobuf_oneof:"Content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proof) Reset() {
	*x = Proof{}
	mi := &file_pb_biscuit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proof) ProtoMessage() {}

func (x *Proof) ProtoReflect() protoreflect.Message {
	mi := &file_pb_biscuit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proof.ProtoReflect.Descriptor instead.
func (*Proof) Descriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{3}
}

func (x *Proof) GetContent() isProof_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Proof) GetNextSecret() []byte {
	if x != nil {
		if x, ok := x.Content.(*Proof_NextSecret); ok {
			return x.NextSecret
		}
	}
	return nil
}

func (x *Proof) GetFinalSignature() []byte {
	if x != nil {
		if x, ok := x.Content.(*Proof_FinalSignature); ok {
			return x.FinalSignature
		}
	}
	return nil
}

type isProof_Content interface {
	isProof_Content()
}

type Proof_NextSecret struct {
	NextSecret []byte `protobuf:"bytes,1,opt,name=nextSecret,oneof"`
}

type Proof_FinalSignature struct {
	FinalSignature []byte `protobuf:"bytes,2,opt,name=finalSignature,oneof"`
}

func (*Proof_NextSecret) isProof_Content() {}

func (*Proof_FinalSignature) isProof_Content() {}

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols" json:"symbols,omitempty"`
	Context       *string                `protobuf:"bytes,2,opt,name=context" json:"context,omitempty"`
	Version       *uint32                `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	FactsV2       []*FactV2              `protobuf:"bytes,4,rep,name=facts_v2,json=factsV2" json:"facts_v2,omitempty"`
	RulesV2       []*RuleV2              `protobuf:"bytes,5,rep,name=rules_v2,json=rulesV2" json:"rules_v2,omitempty"`
	ChecksV2      []*CheckV2             `protobuf:"bytes,6,rep,name=checks_v2,json=checksV2" json:"checks_v2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_pb_biscuit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_pb_biscuit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{4}
}

func (x *Block) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *Block) GetContext() string {
	if x != nil && x.Context != nil {
		return *x.Context
	}
	return ""
}

func (x *Block) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *Block) GetFactsV2() []*FactV2 {
	if x != nil {
		return x.FactsV2
	}
	return nil
}

func (x *Block) GetRulesV2() []*RuleV2 {
	if x != nil {
		return x.RulesV2
	}
	return nil
}

func (x *Block) GetChecksV2() []*CheckV2 {
	if x != nil {
		return x.ChecksV2
	}
	return nil
}

type FactV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Predicate     *PredicateV2           `protobuf:"bytes,1,req,name=predicate" json:"predicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactV2) Reset() {
	*x = FactV2{}
	mi := &file_pb_biscuit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactV2) ProtoMessage() {}

func (x *FactV2) ProtoReflect() protoreflect.Message {
	mi := &file_pb_biscuit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactV2.ProtoReflect.Descriptor instead.
func (*FactV2) Descriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{5}
}

func (x *FactV2) GetPredicate() *PredicateV2 {
	if x != nil {
		return x.Predicate
	}
	return nil
}

type RuleV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Head          *PredicateV2           `protobuf:"bytes,1,req,name=head" json:"head,omitempty"`
	Body          []*PredicateV2         `protobuf:"bytes,2,rep,name=body" json:"body,omitempty"`
	Expressions   []*ExpressionV2        `protobuf:"bytes,3,rep,name=expressions" json:"expressions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleV2) Reset() {
	*x = RuleV2{}
	mi := &file_pb_biscuit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleV2) ProtoMessage() {}

func (x *RuleV2) ProtoReflect() protoreflect.Message {
	mi := &file_pb_biscuit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleV2.ProtoReflect.Descriptor instead.
func (*RuleV2) Descriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{6}
}

func (x *RuleV2) GetHead() *PredicateV2 {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *RuleV2) GetBody() []*PredicateV2 {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RuleV2) GetExpressions() []*ExpressionV2 {
	if x != nil {
		return x.Expressions
	}
	return nil
}

type CheckV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queries       []*RuleV2              `protobuf:"bytes,1,rep,name=queries" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckV2) Reset() {
	*x = CheckV2{}
	mi := &file_pb_biscuit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckV2) ProtoMessage() {}

func (x *CheckV2) ProtoReflect() protoreflect.Message {
	mi := &file_pb_biscuit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckV2.ProtoReflect.Descriptor instead.
func (*CheckV2) Descriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{7}
}

func (x *CheckV2) GetQueries() []*RuleV2 {
	if x != nil {
		return x.Queries
	}
	return nil
}

type PredicateV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *uint64                `protobuf:"varint,1,req,name=name" json:"name,omitempty"`
	Terms         []*TermV2              `protobuf:"bytes,2,rep,name=terms" json:"terms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredicateV2) Reset() {
	*x = PredicateV2{}
	mi := &file_pb_biscuit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredicateV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredicateV2) ProtoMessage() {}

func (x *PredicateV2) ProtoReflect() protoreflect.Message {
	mi := &file_pb_biscuit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredicateV2.ProtoReflect.Descriptor instead.
func (*PredicateV2) Descriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{8}
}

func (x *PredicateV2) GetName() uint64 {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return 0
}

func (x *PredicateV2) GetTerms() []*TermV2 {
	if x != nil {
		return x.Terms
	}
	return nil
}

type TermV2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*TermV2_Variable
	//	*TermV2_Integer
	//	*TermV2_String_
	//	*TermV2_Date
	//	*TermV2_Bytes
	//	*TermV2_Bool
	//	*TermV2_Set
	Content       isTermV2_Content `protobuf_oneof:"Content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermV2) Reset() {
	*x = TermV2{}
	mi := &file_pb_biscuit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermV2) ProtoMessage() {}

func (x *TermV2) ProtoReflect() protoreflect.Message {
	mi := &file_pb_biscuit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermV2.ProtoReflect.Descriptor instead.
func (*TermV2) Descriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{9}
}

func (x *TermV2) GetContent() isTermV2_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *TermV2) GetVariable() uint32 {
	if x != nil {
		if x, ok := x.Content.(*TermV2_Variable); ok {
			return x.Variable
		}
	}
	return 0
}

func (x *TermV2) GetInteger() int64 {
	if x != nil {
		if x, ok := x.Content.(*TermV2_Integer); ok {
			return x.Integer
		}
	}
	return 0
}

func (x *TermV2) GetString_() uint64 {
	if x != nil {
		if x, ok := x.Content.(*TermV2_String_); ok {
			return x.String_
		}
	}
	return 0
}

func (x *TermV2) GetDate() uint64 {
	if x != nil {
		if x, ok := x.Content.(*TermV2_Date); ok {
			return x.Date
		}
	}
	return 0
}

func (x *TermV2) GetBytes() []byte {
	if x != nil {
		if x, ok := x.Content.(*TermV2_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

func (x *TermV2) GetBool() bool {
	if x != nil {
		if x, ok := x.Content.(*TermV2_Bool); ok {
			return x.Bool
		}
	}
	return false
}

func (x *TermV2) GetSet() *TermSet {
	if x != nil {
		if x, ok := x.Content.(*TermV2_Set); ok {
			return x.Set
		}
	}
	return nil
}

type isTermV2_Content interface {
	isTermV2_Content()
}

type TermV2_Variable struct {
	Variable uint32 `protobuf:"varint,1,opt,name=variable,oneof"`
}

type TermV2_Integer struct {
	Integer int64 `protobuf:"varint,2,opt,name=integer,oneof"`
}

type TermV2_String_ struct {
	String_ uint64 `protobuf:"varint,3,opt,name=string,oneof"`
}

type TermV2_Date struct {
	Date uint64 `protobuf:"varint,4,opt,name=date,oneof"`
}

type TermV2_Bytes struct {
	Bytes []byte `protobuf:"bytes,5,opt,name=bytes,oneof"`
}

type TermV2_Bool struct {
	Bool bool `protobuf:"varint,6,opt,name=bool,oneof"`
}

type TermV2_Set struct {
	Set *TermSet `protobuf:"bytes,7,opt,name=set,oneof"`
}

func (*TermV2_Variable) isTermV2_Content() {}

func (*TermV2_Integer) isTermV2_Content() {}

func (*TermV2_String_) isTermV2_Content() {}

func (*TermV2_Date) isTermV2_Content() {}

func (*TermV2_Bytes) isTermV2_Content() {}

func (*TermV2_Bool) isTermV2_Content() {}

func (*TermV2_Set) isTermV2_Content() {}

type TermSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Set           []*TermV2              `protobuf:"bytes,1,rep,name=set" json:"set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermSet) Reset() {
	*x = TermSet{}
	mi := &file_pb_biscuit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermSet) ProtoMessage() {}

func (x *TermSet) ProtoReflect() protoreflect.Message {
	mi := &file_pb_biscuit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermSet.ProtoReflect.Descriptor instead.
func (*TermSet) Descriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{10}
}

func (x *TermSet) GetSet() []*TermV2 {
	if x != nil {
		return x.Set
	}
	return nil
}

type ExpressionV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ops           []*Op                  `protobuf:"bytes,1,rep,name=ops" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpressionV2) Reset() {
	*x = ExpressionV2{}
	mi := &file_pb_biscuit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpressionV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionV2) ProtoMessage() {}

func (x *ExpressionV2) ProtoReflect() protoreflect.Message {
	mi := &file_pb_biscuit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionV2.ProtoReflect.Descriptor instead.
func (*ExpressionV2) Descriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{11}
}

func (x *ExpressionV2) GetOps() []*Op {
	if x != nil {
		return x.Ops
	}
	return nil
}

type Op struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*Op_Value
	//	*Op_Unary
	//	*Op_Binary
	Content       isOp_Content `protobuf_oneof:"Content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Op) Reset() {
	*x = Op{}
	mi := &file_pb_biscuit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Op) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Op) ProtoMessage() {}

func (x *Op) ProtoReflect() protoreflect.Message {
	mi := &file_pb_biscuit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Op.ProtoReflect.Descriptor instead.
func (*Op) Descriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{12}
}

func (x *Op) GetContent() isOp_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Op) GetValue() *TermV2 {
	if x != nil {
		if x, ok := x.Content.(*Op_Value); ok {
			return x.Value
		}
	}
	return nil
}

func (x *Op) GetUnary() *OpUnary {
	if x != nil {
		if x, ok := x.Content.(*Op_Unary); ok {
			return x.Unary
		}
	}
	return nil
}

func (x *Op) GetBinary() *OpBinary {
	if x != nil {
		if x, ok := x.Content.(*Op_Binary); ok {
			return x.Binary
		}
	}
	return nil
}

type isOp_Content interface {
	isOp_Content()
}

type Op_Value struct {
	Value *TermV2 `protobuf:"bytes,1,opt,name=value,oneof"`
}

type Op_Unary struct {
	Unary *OpUnary `protobuf:"bytes,2,opt,name=unary,oneof"`
}

type Op_Binary struct {
	Binary *OpBinary `protobuf:"bytes,3,opt,name=Binary,oneof"`
}

func (*Op_Value) isOp_Content() {}

func (*Op_Unary) isOp_Content() {}

func (*Op_Binary) isOp_Content() {}

type OpUnary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          *OpUnary_Kind          `protobuf:"varint,1,req,name=kind,enum=OpUnary_Kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpUnary) Reset() {
	*x = OpUnary{}
	mi := &file_pb_biscuit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpUnary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpUnary) ProtoMessage() {}

func (x *OpUnary) ProtoReflect() protoreflect.Message {
	mi := &file_pb_biscuit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpUnary.ProtoReflect.Descriptor instead.
func (*OpUnary) Descriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{13}
}

func (x *OpUnary) GetKind() OpUnary_Kind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return OpUnary_Negate
}

type OpBinary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          *OpBinary_Kind         `protobuf:"varint,1,req,name=kind,enum=OpBinary_Kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpBinary) Reset() {
	*x = OpBinary{}
	mi := &file_pb_biscuit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpBinary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpBinary) ProtoMessage() {}

func (x *OpBinary) ProtoReflect() protoreflect.Message {
	mi := &file_pb_biscuit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpBinary.ProtoReflect.Descriptor instead.
func (*OpBinary) Descriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{14}
}

func (x *OpBinary) GetKind() OpBinary_Kind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return OpBinary_LessThan
}

type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queries       []*RuleV2              `protobuf:"bytes,1,rep,name=queries" json:"queries,omitempty"`
	Kind          *Policy_Kind           `protobuf:"varint,2,req,name=kind,enum=Policy_Kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_pb_biscuit_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_pb_biscuit_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{15}
}

func (x *Policy) GetQueries() []*RuleV2 {
	if x != nil {
		return x.Queries
	}
	return nil
}

func (x *Policy) GetKind() Policy_Kind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return Policy_Allow
}

type AuthorizerPolicies struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols" json:"symbols,omitempty"`
	Version       *uint32                `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	Facts         []*FactV2              `protobuf:"bytes,3,rep,name=facts" json:"facts,omitempty"`
	Rules         []*RuleV2              `protobuf:"bytes,4,rep,name=rules" json:"rules,omitempty"`
	Checks        []*CheckV2             `protobuf:"bytes,5,rep,name=checks" json:"checks,omitempty"`
	Policies      []*Policy              `protobuf:"bytes,6,rep,name=policies" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizerPolicies) Reset() {
	*x = AuthorizerPolicies{}
	mi := &file_pb_biscuit_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizerPolicies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizerPolicies) ProtoMessage() {}

func (x *AuthorizerPolicies) ProtoReflect() protoreflect.Message {
	mi := &file_pb_biscuit_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizerPolicies.ProtoReflect.Descriptor instead.
func (*AuthorizerPolicies) Descriptor() ([]byte, []int) {
	return file_pb_biscuit_proto_rawDescGZIP(), []int{16}
}

func (x *AuthorizerPolicies) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *AuthorizerPolicies) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *AuthorizerPolicies) GetFacts() []*FactV2 {
	if x != nil {
		return x.Facts
	}
	return nil
}

func (x *AuthorizerPolicies) GetRules() []*RuleV2 {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *AuthorizerPolicies) GetChecks() []*CheckV2 {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *AuthorizerPolicies) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

var File_pb_biscuit_proto protoreflect.FileDescriptor

const file_pb_biscuit_proto_rawDesc = "" +
	"\n" +
	"\x10pb/biscuit.proto\"\x97\x01\n" +
	"\aBiscuit\x12\x1c\n" +
	"\trootKeyId\x18\x01 \x01(\rR\trootKeyId\x12*\n" +
	"\tauthority\x18\x02 \x02(\v2\f.SignedBlockR\tauthority\x12$\n" +
	"\x06blocks\x18\x03 \x03(\v2\f.SignedBlockR\x06blocks\x12\x1c\n" +
	"\x05proof\x18\x04 \x02(\v2\x06.ProofR\x05proof\"g\n" +
	"\vSignedBlock\x12\x14\n" +
	"\x05block\x18\x01 \x02(\fR\x05block\x12$\n" +
	"\anextKey\x18\x02 \x02(\v2\n" +
	".PublicKeyR\anextKey\x12\x1c\n" +
	"\tsignature\x18\x03 \x02(\fR\tsignature\"k\n" +
	"\tPublicKey\x122\n" +
	"\talgorithm\x18\x01 \x02(\x0e2\x14.PublicKey.AlgorithmR\talgorithm\x12\x10\n" +
	"\x03key\x18\x02 \x02(\fR\x03key\"\x18\n" +
	"\tAlgorithm\x12\v\n" +
	"\aEd25519\x10\x00\"^\n" +
	"\x05Proof\x12 \n" +
	"\n" +
	"nextSecret\x18\x01 \x01(\fH\x00R\n" +
	"nextSecret\x12(\n" +
	"\x0efinalSignature\x18\x02 \x01(\fH\x00R\x0efinalSignatureB\t\n" +
	"\aContent\"\xc4\x01\n" +
	"\x05Block\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\x12\"\n" +
	"\bfacts_v2\x18\x04 \x03(\v2\a.FactV2R\afactsV2\x12\"\n" +
	"\brules_v2\x18\x05 \x03(\v2\a.RuleV2R\arulesV2\x12%\n" +
	"\tchecks_v2\x18\x06 \x03(\v2\b.CheckV2R\bchecksV2\"4\n" +
	"\x06FactV2\x12*\n" +
	"\tpredicate\x18\x01 \x02(\v2\f.PredicateV2R\tpredicate\"}\n" +
	"\x06RuleV2\x12 \n" +
	"\x04head\x18\x01 \x02(\v2\f.PredicateV2R\x04head\x12 \n" +
	"\x04body\x18\x02 \x03(\v2\f.PredicateV2R\x04body\x12/\n" +
	"\vexpressions\x18\x03 \x03(\v2\r.ExpressionV2R\vexpressions\",\n" +
	"\aCheckV2\x12!\n" +
	"\aqueries\x18\x01 \x03(\v2\a.RuleV2R\aqueries\"@\n" +
	"\vPredicateV2\x12\x12\n" +
	"\x04name\x18\x01 \x02(\x04R\x04name\x12\x1d\n" +
	"\x05terms\x18\x02 \x03(\v2\a.TermV2R\x05terms\"\xc9\x01\n" +
	"\x06TermV2\x12\x1c\n" +
	"\bvariable\x18\x01 \x01(\rH\x00R\bvariable\x12\x1a\n" +
	"\ainteger\x18\x02 \x01(\x03H\x00R\ainteger\x12\x18\n" +
	"\x06string\x18\x03 \x01(\x04H\x00R\x06string\x12\x14\n" +
	"\x04date\x18\x04 \x01(\x04H\x00R\x04date\x12\x16\n" +
	"\x05bytes\x18\x05 \x01(\fH\x00R\x05bytes\x12\x14\n" +
	"\x04bool\x18\x06 \x01(\bH\x00R\x04bool\x12\x1c\n" +
	"\x03set\x18\a \x01(\v2\b.TermSetH\x00R\x03setB\t\n" +
	"\aContent\"$\n" +
	"\aTermSet\x12\x19\n" +
	"\x03set\x18\x01 \x03(\v2\a.TermV2R\x03set\"%\n" +
	"\fExpressionV2\x12\x15\n" +
	"\x03ops\x18\x01 \x03(\v2\x03.OpR\x03ops\"w\n" +
	"\x02Op\x12\x1f\n" +
	"\x05value\x18\x01 \x01(\v2\a.TermV2H\x00R\x05value\x12 \n" +
	"\x05unary\x18\x02 \x01(\v2\b.OpUnaryH\x00R\x05unary\x12#\n" +
	"\x06Binary\x18\x03 \x01(\v2\t.OpBinaryH\x00R\x06BinaryB\t\n" +
	"\aContent\"X\n" +
	"\aOpUnary\x12!\n" +
	"\x04kind\x18\x01 \x02(\x0e2\r.OpUnary.KindR\x04kind\"*\n" +
	"\x04Kind\x12\n" +
	"\n" +
	"\x06Negate\x10\x00\x12\n" +
	"\n" +
	"\x06Parens\x10\x01\x12\n" +
	"\n" +
	"\x06Length\x10\x02\"\x97\x02\n" +
	"\bOpBinary\x12\"\n" +
	"\x04kind\x18\x01 \x02(\x0e2\x0e.OpBinary.KindR\x04kind\"\xe6\x01\n" +
	"\x04Kind\x12\f\n" +
	"\bLessThan\x10\x00\x12\x0f\n" +
	"\vGreaterThan\x10\x01\x12\x0f\n" +
	"\vLessOrEqual\x10\x02\x12\x12\n" +
	"\x0eGreaterOrEqual\x10\x03\x12\t\n" +
	"\x05Equal\x10\x04\x12\f\n" +
	"\bContains\x10\x05\x12\n" +
	"\n" +
	"\x06Prefix\x10\x06\x12\n" +
	"\n" +
	"\x06Suffix\x10\a\x12\t\n" +
	"\x05Regex\x10\b\x12\a\n" +
	"\x03Add\x10\t\x12\a\n" +
	"\x03Sub\x10\n" +
	"\x12\a\n" +
	"\x03Mul\x10\v\x12\a\n" +
	"\x03Div\x10\f\x12\a\n" +
	"\x03And\x10\r\x12\x06\n" +
	"\x02Or\x10\x0e\x12\x10\n" +
	"\fIntersection\x10\x0f\x12\t\n" +
	"\x05Union\x10\x10\x12\f\n" +
	"\bNotEqual\x10\x11\"j\n" +
	"\x06Policy\x12!\n" +
	"\aqueries\x18\x01 \x03(\v2\a.RuleV2R\aqueries\x12 \n" +
	"\x04kind\x18\x02 \x02(\x0e2\f.Policy.KindR\x04kind\"\x1b\n" +
	"\x04Kind\x12\t\n" +
	"\x05Allow\x10\x00\x12\b\n" +
	"\x04Deny\x10\x01\"\xcd\x01\n" +
	"\x12AuthorizerPolicies\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12\x1d\n" +
	"\x05facts\x18\x03 \x03(\v2\a.FactV2R\x05facts\x12\x1d\n" +
	"\x05rules\x18\x04 \x03(\v2\a.RuleV2R\x05rules\x12 \n" +
	"\x06checks\x18\x05 \x03(\v2\b.CheckV2R\x06checks\x12#\n" +
	"\bpolicies\x18\x06 \x03(\v2\a.PolicyR\bpoliciesB\x06Z\x04.;pb"

var (
	file_pb_biscuit_proto_rawDescOnce sync.Once
	file_pb_biscuit_proto_rawDescData []byte
)

func file_pb_biscuit_proto_rawDescGZIP() []byte {
	file_pb_biscuit_proto_rawDescOnce.Do(func() {
		file_pb_biscuit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_biscuit_proto_rawDesc), len(file_pb_biscuit_proto_rawDesc)))
	})
	return file_pb_biscuit_proto_rawDescData
}

var file_pb_biscuit_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_pb_biscuit_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pb_biscuit_proto_goTypes = []any{
	(PublicKey_Algorithm)(0),   // 0: PublicKey.Algorithm
	(OpUnary_Kind)(0),          // 1: OpUnary.Kind
	(OpBinary_Kind)(0),         // 2: OpBinary.Kind
	(Policy_Kind)(0),           // 3: Policy.Kind
	(*Biscuit)(nil),            // 4: Biscuit
	(*SignedBlock)(nil),        // 5: SignedBlock
	(*PublicKey)(nil),          // 6: PublicKey
	(*Proof)(nil),              // 7: Proof
	(*Block)(nil),              // 8: Block
	(*FactV2)(nil),             // 9: FactV2
	(*RuleV2)(nil),             // 10: RuleV2
	(*CheckV2)(nil),            // 11: CheckV2
	(*PredicateV2)(nil),        // 12: PredicateV2
	(*TermV2)(nil),             // 13: TermV2
	(*TermSet)(nil),            // 14: TermSet
	(*ExpressionV2)(nil),       // 15: ExpressionV2
	(*Op)(nil),                 // 16: Op
	(*OpUnary)(nil),            // 17: OpUnary
	(*OpBinary)(nil),           // 18: OpBinary
	(*Policy)(nil),             // 19: Policy
	(*AuthorizerPolicies)(nil), // 20: AuthorizerPolicies
}
var file_pb_biscuit_proto_depIdxs = []int32{
	5,  // 0: Biscuit.authority:type_name -> SignedBlock
	5,  // 1: Biscuit.blocks:type_name -> SignedBlock
	7,  // 2: Biscuit.proof:type_name -> Proof
	6,  // 3: SignedBlock.nextKey:type_name -> PublicKey
	0,  // 4: PublicKey.algorithm:type_name -> PublicKey.Algorithm
	9,  // 5: Block.facts_v2:type_name -> FactV2
	10, // 6: Block.rules_v2:type_name -> RuleV2
	11, // 7: Block.checks_v2:type_name -> CheckV2
	12, // 8: FactV2.predicate:type_name -> PredicateV2
	12, // 9: RuleV2.head:type_name -> PredicateV2
	12, // 10: RuleV2.body:type_name -> PredicateV2
	15, // 11: RuleV2.expressions:type_name -> ExpressionV2
	10, // 12: CheckV2.queries:type_name -> RuleV2
	13, // 13: PredicateV2.terms:type_name -> TermV2
	14, // 14: TermV2.set:type_name -> TermSet
	13, // 15: TermSet.set:type_name -> TermV2
	16, // 16: ExpressionV2.ops:type_name -> Op
	13, // 17: Op.value:type_name -> TermV2
	17, // 18: Op.unary:type_name -> OpUnary
	18, // 19: Op.Binary:type_name -> OpBinary
	1,  // 20: OpUnary.kind:type_name -> OpUnary.Kind
	2,  // 21: OpBinary.kind:type_name -> OpBinary.Kind
	10, // 22: Policy.queries:type_name -> RuleV2
	3,  // 23: Policy.kind:type_name -> Policy.Kind
	9,  // 24: AuthorizerPolicies.facts:type_name -> FactV2
	10, // 25: AuthorizerPolicies.rules:type_name -> RuleV2
	11, // 26: AuthorizerPolicies.checks:type_name -> CheckV2
	19, // 27: AuthorizerPolicies.policies:type_name -> Policy
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_pb_biscuit_proto_init() }
func file_pb_biscuit_proto_init() {
	if File_pb_biscuit_proto != nil {
		return
	}
	file_pb_biscuit_proto_msgTypes[3].OneofWrappers = []any{
		(*Proof_NextSecret)(nil),
		(*Proof_FinalSignature)(nil),
	}
	file_pb_biscuit_proto_msgTypes[9].OneofWrappers = []any{
		(*TermV2_Variable)(nil),
		(*TermV2_Integer)(nil),
		(*TermV2_String_)(nil),
		(*TermV2_Date)(nil),
		(*TermV2_Bytes)(nil),
		(*TermV2_Bool)(nil),
		(*TermV2_Set)(nil),
	}
	file_pb_biscuit_proto_msgTypes[12].OneofWrappers = []any{
		(*Op_Value)(nil),
		(*Op_Unary)(nil),
		(*Op_Binary)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_biscuit_proto_rawDesc), len(file_pb_biscuit_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_biscuit_proto_goTypes,
		DependencyIndexes: file_pb_biscuit_proto_depIdxs,
		EnumInfos:         file_pb_biscuit_proto_enumTypes,
		MessageInfos:      file_pb_biscuit_proto_msgTypes,
	}.Build()
	File_pb_biscuit_proto = out.File
	file_pb_biscuit_proto_goTypes = nil
	file_pb_biscuit_proto_depIdxs = nil
}
